# swagger configuration file

# values in the swagger hash are system configuration for swagger
swagger:
  #TODO: Remove this line if error handling works correctly.
  # mapErrorsToJson: true
  docEndpoints:
    raw: /swagger

# any other values in this file are just loaded into the config for application access...

database:
  user: root
  password: ''
  database: test123 # database name
  host: localhost
  port:
  pool:
    min: 0
    max: 10
