# swagger configuration file

# values in the swagger hash are system configuration for swagger
swagger:
  #TODO: Remove this line if error handling works correctly.
  # mapErrorsToJson: true
  docEndpoints:
    raw: /swagger

# any other values in this file are just loaded into the config for application access...

mysqlDatabase:
  user: root
  password: ''
  database: test123 # database name
  host: localhost
  port:
  pool:
    min: 0
    max: 10

mongoDatabase:
  url: mongodb://localhost:27017/local
